{{- if .Values.gatewayApi.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "voe-power-outages.fullname" . }}
  labels:
    {{- include "voe-power-outages.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.gatewayApi.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.gatewayApi.hostnames | nindent 4 }}
  rules:
    - matches:
        {{- toYaml .Values.gatewayApi.matches | nindent 8 }}
      backendRefs:
        - name: {{ include "voe-power-outages.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
