{{- if .Values.secretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voe-power-outages.fullname" . }}-secret
  labels:
    {{- include "voe-power-outages.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secretData | nindent 2 }}
{{- end }}
