{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "voe-power-outages.serviceAccountName" . }}
  labels:
    {{- include "voe-power-outages.labels" . | nindent 4 }}
{{- end }}
